# Generated by Django 3.2.4 on 2021-08-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
    ]
