# Generated by Django 3.2.4 on 2021-08-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('web', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('vacancy', models.IntegerField(default=1)),
                ('job_time', models.CharField(choices=[(0, 'Part Time'), (1, 'Full Time')], max_length=10)),
                ('salary_type', models.CharField(choices=[(0, 'Yearly'), (1, 'Monthly')], max_length=10)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_date', models.DateField(auto_now_add=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.company')),
            ],
        ),
    ]
