# Generated by Django 3.2.4 on 2021-08-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210811_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.CharField(default='tour', max_length=50),
        ),
    ]
