# Generated by Django 3.2.4 on 2021-08-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_time',
            field=models.CharField(choices=[('part_time', 'Part Time'), ('full_time', 'Full Time')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('yearly', 'Yearly'), ('monthly', 'Monthly')], max_length=10),
        ),
    ]
