# Generated by Django 3.2.4 on 2021-08-11 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_job_job_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 11, 11, 23, 0, 565812, tzinfo=utc)),
        ),
    ]
