# Generated by Django 3.2.4 on 2021-08-11 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20210811_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['posted_date']},
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 11, 12, 6, 3, 624694, tzinfo=utc)),
        ),
    ]
