# Generated by Django 3.2.4 on 2021-08-11 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20210811_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 11, 12, 7, 36, 714030, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
